name: dothings
on: push

jobs:
  test:
    name: os setup?
    strategy:
      matrix:
        os: ubuntu-latest
        dc: dmd-latest
    runs-on: ubuntu-latest
    steps:
      -name : do nothing of use
      run: cat hello.d > bye.d