name: dothings
on: push

jobs:
  dothings:
    name: os setup?
      strategy:
        matrix:
          os: ubuntu-latest
          dc: dmd-latest
      steps:
        - name: install d compiler?
        uses: dlang-community/setup-dlang@v1
        with: dmd-latest
        
        -name : run hello world?
        run: dmd -run hello.d >out