name: dothings
on: push

jobs:
  test:
    name: os setup?
    strategy:
      matrix:
        os: ubuntu-latest
        dc: dmd-latest
    runs-on:ubuntu-latest
    steps:
      - name: install d compiler?
      uses: dlang-community/setup-dlang@v1
      with: dmd-latest
      
      -name : run hello world?
      run: dmd -run hello.d >out