name: dothings
on: push

jobs:
  test:
    name: os setup?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat hello.d > bye.d
      

            
      - run: cat bye.d
      - run: dmd bye.d
      - run: dmd -run hello.d