name: dothings
on: push

jobs:
  test:
    name: os setup?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat hello.d > bye.d
      - name: attempt to install compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
      - run: cat bye.d